image: gitpod/workspace-mysql #CONFIGURANDO A IMAGEM DO GITPOD PARA INCIAR COM O MYSQL

tasks: #ABRE A LISTA DE TAREFAS
  - init: mysql -u root -e "CREATE DATABASE applicationdb" # TAREFA, AO INCIAR O AMIENTE QUE ACESSA O USURARIO (ROOT) 